# Generated by Django 5.1.2 on 2026-07-06 00:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medicineevent_laydownevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[("medicine", "Medicine"), ("bed", "Bed")],
                        max_length=32,
                        verbose_name="Banner type",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Reminder date"
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        default=timezone.localtime,
                        verbose_name="Dismissed at",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_dismissal",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "feeding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_dismissal",
                        to="core.feeding",
                        verbose_name="Feeding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner dismissal",
                "verbose_name_plural": "Banner dismissals",
                "ordering": ["-dismissed_at"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
